# https://nixpacks.com/docs/configuration/file
# Set up some variables to minimize annoyance
[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false' # Disable update notifications in production
NPM_CONFIG_FUND = 'false'            # Disable funding notifications in production

# Download Caddy from Nix
[phases.caddy]
dependsOn = [
  'setup',
] # Ensure this phase runs after the 'setup' phase
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4
nixPkgs = ['caddy'] # Install Caddy as a Nix package

# Start the Caddy web server without using a Caddyfile
[start]
cmd = 'exec caddy file-server --root dist --listen :${PORT:-3000} 2>&1' # Start Caddy with command-line options
